webtalk_init -webtalk_dir /home/zx1412/EL6463Project/EL6463Project.sim/sim_1/behav/xsim/xsim.dir/NYU_6463_RV32I_Processor_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Dec 10 13:21:21 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211974547_1777556214_210730127_066" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "564742f3-d093-4b72-b24c-7e110d55c434" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "38ed18faed2d4de0be3f4b4a7d0c2ddf" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "6" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "RedHatEnterpriseServer" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Red Hat Enterprise Linux Server release 7.9 (Maipo)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD EPYC 7551 32-Core Processor" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2000.000 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "540.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "2 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.15_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "126720_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3408759789 -regid "211974547_1777556214_210730127_066" -xml /home/zx1412/EL6463Project/EL6463Project.sim/sim_1/behav/xsim/xsim.dir/NYU_6463_RV32I_Processor_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/zx1412/EL6463Project/EL6463Project.sim/sim_1/behav/xsim/xsim.dir/NYU_6463_RV32I_Processor_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/zx1412/EL6463Project/EL6463Project.sim/sim_1/behav/xsim/xsim.dir/NYU_6463_RV32I_Processor_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
